print("True and True ? {}".format(True and True))
print("False and True ? {}".format(False and True))
print("1 == 1 and 2 == 2 ? {}".format(1 == 1 and 2 == 2))
print('"test" == "test" ? {}'.format("test" == "test"))
print("1 == 1 or 2 != 1 ? {}".format(1 == 1 or 2 != 1))
print("True and 1 == 1 ? {}".format(True and 1 == 1))
print("False and 0 != 0 ? {}".format(False and 0 != 0))
print("True or 1 == 1 ? {}".format(True or 1 == 1))
print('"test" == "testing" ? {}'.format("test" == "testing"))
print("1 != 0 and 2 == 1 ? {}".format(1 != 0 and 2 == 1))
print('"test" != "testing" ? {}'.format("test" != "testing"))
print("'test' == 1 ? {}".format('test' == 1))
print("not (True and False) ? {}".format(not (True and False)))
print("not (1 == 1 and 0 != 1) ? {}".format(not (1 == 1 and 0 != 1)))
print("not (10 == 1 or 1000 == 1000) ? {}".format(not (10 == 1 or 1000 == 1000)))
print("not (1 != 10 or 3 == 4) ? {}".format(not (1 != 10 or 3 == 4)))
print("not ('testing' == 'testing' and 'Zed' == 'Cool Guy') ? {}".format(not ('testing' == 'testing' and 'Zed' == 'Cool Guy')))
print("1 == 1 and (not ('testing' == 1 or 1 == 0)) ? {}".format(1 == 1 and (not ('testing' == 1 or 1 == 0))))
print("'chunky' == 'bacon' and (not (3 == 4 or 3 == 3)) ? {}".format('chunky' == 'bacon' and (not (3 == 4 or 3 == 3))))
print("3 == 3 and (not ('testing' == 'testing' or 'python' == 'fun')) ? {}".format(3 == 3 and (not ('testing' == 'testing' or 'python' == 'fun'))))